name: Check build

on:
  push:
    branches:
      - master
    
  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 0 * * *'
  
jobs:
  archlinux:
    name: on Archlinux
    runs-on: ubuntu-20.04
    container: docker.io/library/archlinux:latest
    steps:
      - name: Checkout qt5-ukui-platformtheme source code
        uses: actions/checkout@v2
      - name: Refresh pacman repository
        run: pacman -Sy
      - name: Install build dependencies
        run: pacman -S --noconfirm base-devel qt5-base gsettings-qt kwindowsystem qt5-tools dconf
      - name: QMake configure & Make
        run: |
          mkdir build;
          cd build;
          qmake-qt5 ..;
          make -j$(nproc);
  debian:
    name: on Debian Sid
    runs-on: ubuntu-20.04
    container: docker.io/library/debian:sid
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout qt5-ukui-platformtheme source code
        uses: actions/checkout@v2
      - name: Update apt repository
        run: apt-get update -y
      - name: Install build dependcies
        run: apt-get install -y build-essential qt5-default qttools5-dev-tools qtmultimedia5-dev debhelper-compat pkg-kde-tools libglib2.0-dev libqt5x11extras5-dev libkf5windowsystem-dev libgsettings-qt-dev pkg-config qt5-qmake qtbase5-dev qtbase5-dev-tools qtbase5-private-dev qtchooser qttools5-dev-tools
      - name: QMake configure & Make
        run: |
          mkdir build;
          cd build;
          qmake ..;
          make -j$(nproc);
  
  fedora:
    name: on Fedora 32
    runs-on: ubuntu-20.04
    container: docker.io/library/fedora:32
    steps:
      - name: Checkout qt5-ukui-platformtheme source code
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: dnf install -y which gcc gcc-c++ make cmake cmake-rpm-macros autoconf automake intltool rpm-build qt5-rpm-macros  glib2-devel qt5-qtx11extras-devel kf5-kwindowsystem-devel gsettings-desktop-schemas-devel qt5-qtbase-devel qt5-qtbase-private-devel qt5-qttools-devel gsettings-qt-devel
      - name: QMake configure & Make
        run: |
          mkdir build;
          cd build;
          qmake-qt5 ..;
          make -j$(nproc);
  ubuntu:
    name: on Ubuntu 20.04
    runs-on: ubuntu-20.04
    container: docker.io/library/ubuntu:focal
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout qt5-ukui-platformtheme source code
        uses: actions/checkout@v2
      - name: Update apt repository
        run: apt-get update -y
      - name: Install build dependcies
        run: apt-get install -y build-essential qt5-default qttools5-dev-tools qtmultimedia5-dev debhelper-compat pkg-kde-tools libglib2.0-dev libqt5x11extras5-dev libkf5windowsystem-dev libgsettings-qt-dev pkg-config qt5-qmake qtbase5-dev qtbase5-dev-tools qtbase5-private-dev qtchooser qttools5-dev-tools
      - name: QMake configure & Make
        run: |
          mkdir build;
          cd build;
          qmake ..;
          make -j$(nproc);