name: build

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout qt5-ukui-platformtheme source
        uses: actions/checkout@v2

      - name: Update apt repository
        run: sudo apt-get update -y

      - name: Install latest Qt5
        run: sudo apt-get -y install build-essential qt5-default qttools5-dev-tools qtmultimedia5-dev

      - name: Instal dependcies
        run: sudo apt-get install debhelper-compat pkg-kde-tools libglib2.0-dev libqt5x11extras5-dev libkf5windowsystem-dev libgsettings-qt-dev pkg-config qt5-qmake qtbase5-dev qtbase5-dev-tools qtbase5-private-dev qtchooser qttools5-dev-tools

      - name: QMake configure & Make
        run: mkdir build && cd build && qmake .. && make -j$(nproc)
